export const STATE_IDLE = 'STATE_IDLE';
export const STATE_CREATING = 'STATE_CREATING';
export const STATE_JOINING = 'STATE_JOINING';
export const STATE_JOINED = 'STATE_JOINED';
export const STATE_LEAVING = 'STATE_LEAVING';
export const STATE_ERROR = 'STATE_ERROR';
export const STATE_HAIRCHECK = 'STATE_HAIRCHECK';
